version: '3.7'

services:
    postgres:
        image: postgres
        container_name: nlw-heat-db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: docker
            POSTGRES_DB: nlw-heat-db
        ports:
            - '5432:5432'
        restart: unless-stopped

    app:
        container_name: nlw-heat-backend
        build:
            dockerfile: Dockerfile
            context: .
        environment:
            DATABASE_URL: 'postgresql://postgres:docker@postgres:5432/nlw-heat-db?schema=public'
            GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
            GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
            SECRET_HASH: ${SECRET_HASH}
        ports:
            - ${API_PORT}:${API_PORT}
            - '5555:5555'
        depends_on:
            - postgres
